### ISSUE TITLE
MITObim says it is starting but nothing happens

### ISSUE THREAD

**Issue by mangsta** [chrishah/MITObim#14] opened 2015-11-21 02:19 UTC
I am doing tutorial number 1.  I have downloaded mira_4.9.5_2_linux-gnu_x86_64_static.tar.bz2/download and MITObim 1.8.

Why does MITObim say it is starting but nothing happens?

MITObim will not overwrite an existing directory: iteration1

MITObim - mitochondrial baiting and iterative mapping
version 1.8
author: Christoph Hahn, (c) 2012-2015

Full command run:
../../fslhome/mangsta/Genome_Assembly/MITObim/MITObim_1.8.pl -start 1 -end 10 -sample testpool -ref Salpinus_mt_genome -readpool reads.fastq -maf initial-mapping-testpool-to-Salpinus-mt_assembly/initial-mapping-testpool-to-Salpinus-mt_d_results/initial-mapping-testpool-to-Salpinus-mt_out.maf

All paramters seem to make sense:
startiteration: 1
enditeration: 10
sample: testpool
refname: Salpinus_mt_genome
readpool: /bluehome3/mangsta/Genome_Assembly/MITObim/testdata1/Tthymallus-150bp-300sd50-interleaved.fastq
maf: /tmp/tutorial1/initial-mapping-testpool-to-Salpinus-mt_assembly/initial-mapping-testpool-to-Salpinus-mt_d_results/initial-mapping-testpool-to-Salpinus-mt_out.maf
quick: 0
paired: 0 (off=0, on=1)
assembly mode: 0 (mapping=0, denovo=1)
verbose: 0 (off=0, on=1)
split: 0 (off=0, on=1)
minimum avg. coverage: 0 (off=0)
clean: 0 (off=0, on=1)
trim reads: 0 (off=0, on=1)
trim overhang: 0 (no=0, yes=1)
platform: SOLEXA
kmer baiting: 31
number of missmatches in mapping assembly: default (15% of average read length loaded)
proofreading: off

Starting MITObim
~

**Comment by chrishah** [comment] 2015-11-21 10:09
Hi,

You will have to remove 'iteration1' directory from the previous run first. MITObim will not overwrite it and stops.

MITObim has only been tested with the stable version MIRA 4.0.2, so I recommend using this version.

Thanks!
Christoph

**Comment by mangsta** [comment] 2015-11-22 02:26
Ok thanks! I'll try that.  Also, the same problem occurred the first time that I attempted to run MITObim (before there was a directory 'iteration 1' .  Any ideas on why that would be?

Sent from my iPhone


On Nov 21, 2015, at 3:09 AM, Christoph Hahn <notifications@github.com> wrote:


Hi,You will have to remove 'iteration1' directory from the previous run first. MITObim will not overwrite it and stops.MITObim has only been tested with the stable version MIRA 4.0.2, so I recommend using this version.Thanks!
Christoph—

**Comment by mangsta** [comment] 2015-11-22 02:33
Both of these versions are stable correct?mira-4.0.2.tar.bz2mira_4.0.2_linux-gnu_x86_64_static.tar.bz2
So it shouldn't matter which I use.  
Thanks,Ryan 


    On Saturday, November 21, 2015 7:26 PM, Ryan Mangelson <rmangelson@yahoo.com> wrote:
 

 Ok thanks! I'll try that.  Also, the same problem occurred the first time that I attempted to run MITObim (before there was a directory 'iteration 1' .  Any ideas on why that would be?

Sent from my iPhone


On Nov 21, 2015, at 3:09 AM, Christoph Hahn <notifications@github.com> wrote:


Hi,You will have to remove 'iteration1' directory from the previous run first. MITObim will not overwrite it and stops.MITObim has only been tested with the stable version MIRA 4.0.2, so I recommend using this version.Thanks!
Christoph—

**Comment by chrishah** [comment] 2015-11-22 09:22
Hi,
Yes, both are mira 4.0.2, the difference:
mira_4.0.2_linux-gnu_x86_64_static.tar.bz2 - contains precompiled binaries for linux systems.
mira-4.0.2.tar.bz2 - is the source code of the same version in case you want to compile yourself.

The error message you sent previously was caused by the presence of iteration1 directory. It says:
'MITObim will not overwrite an existing directory: iteration1'

If you got an error when you ran it the first time something else must have caused the error. Hard to say what it was without seeing the error message, though. Please just try again after getting MIRA 4.0.2 running. Make sure that no directories from previous runs are present and if you get an error send it over - Thanks!

cheers,
Christoph

**Comment by mangsta** [comment] 2015-11-23 16:09
I redownloaded MITObim4.0.2 and it worked great!!  Thanks so much for the help.

Regards,
Ryan

**Comment by chrishah** [comment] 2015-11-23 19:46
I am glad to hear it - closing this issue then!

Good luck Ryan!

cheers,
Christoph

**Closed by chrishah** 2015-11-23 19:46 UTC
